<?php

declare(strict_types=1);

$finder = PhpCsFixer\Finder::create()
	->exclude('vendor')
	->in(__DIR__)
	->name('*.php')
;

$config = new PhpCsFixer\Config();
return $config->setRules([
	'@PSR2' => true,
	'@PSR12' => true,
	'array_syntax' => ['syntax' => 'short'],
	'binary_operator_spaces' => ['default' => 'single_space', 'operators' => ['=' => 'align_single_space_minimal']],
	'blank_line_after_namespace' => true,
	'blank_line_after_opening_tag' => true,
	'blank_line_before_statement' => ['statements' => ['return', 'throw', 'try']],
	'blank_lines_before_namespace' => ['min_line_breaks' => 1, 'max_line_breaks' => 2],
	'braces' => ['allow_single_line_anonymous_class_with_empty_body' => true, 'allow_single_line_closure' => true, 'position_after_functions_and_oop_constructs' => 'next', 'position_after_control_structures' => 'same', 'position_after_anonymous_constructs' => 'same'],
	'class_attributes_separation' => ['elements' => ['const' => 'one', 'method' => 'one', 'property' => 'one']],
	'class_definition' => ['multi_line_extends_each_single_line' => true, 'single_item_single_line' => true, 'single_line' => true],
	'clean_namespace' => true,
	'constant_case' => ['case' => 'lower'],
	'comment_to_phpdoc' => ['ignored_tags' => []],
	'concat_space' => ['spacing' => 'none'],
	'declare_equal_normalize' => ['space' => 'none'],
	'declare_parentheses' => true,
	'elseif' => true,
	'encoding' => true,
	'full_opening_tag' => true,
	'function_declaration' => ['closure_function_spacing' => 'one'],
	'function_typehint_space' => true,
	'general_phpdoc_tag_rename' => ['replacements' => ['inheritDocs' => 'inheritDoc']],
	'heredoc_to_nowdoc' => true,
	'include' => true,
	'indentation_type' => true,
	'line_ending' => true,
	'linebreak_after_opening_tag' => true,
	'lowercase_cast' => true,
	'lowercase_keywords' => true,
	'method_argument_space' => [
		'on_multiline' => 'ensure_fully_multiline',
		'keep_multiple_spaces_after_comma' => false,
		'after_heredoc' => false,
	],
	'method_chaining_indentation' => true,
	'multiline_comment_opening_closing' => true,
	'multiline_whitespace_before_semicolons' => ['strategy' => 'no_multi_line'],
	'no_blank_lines_after_class_opening' => true,
	'no_blank_lines_after_phpdoc' => true,
	'no_closing_tag' => true,
	'no_empty_comment' => true,
	'no_empty_phpdoc' => true,
	'no_empty_statement' => true,
	'no_extra_blank_lines' => [
		'tokens' => [
			'extra',
			'curly_brace_block',
			'parenthesis_brace_block',
			'square_brace_block',
			'throw',
			'use',
		],
	],
	'no_leading_namespace_whitespace' => true,
	'no_multiline_whitespace_around_double_arrow' => true,
	'no_spaces_after_function_name' => true,
	'no_spaces_around_offset' => ['positions' => ['inside']],
	'no_spaces_inside_parenthesis' => true,
	'no_trailing_whitespace' => true,
	'no_trailing_whitespace_in_comment' => true,
	'no_unused_imports' => true,
	'no_whitespace_before_comma_in_array' => true,
	'no_whitespace_in_blank_line' => true,
	'normalize_index_brace' => true,
	'ordered_imports' => ['sort_algorithm' => 'alpha'],
	'phpdoc_add_missing_param_annotation' => true,
	'phpdoc_align' => ['align' => 'left'],
	'phpdoc_indent' => true,
	'phpdoc_inline_tag_normalizer' => true,
	'phpdoc_line_span' => ['const' => 'single', 'property' => 'single', 'method' => 'multi'],
	'phpdoc_no_access' => true,
	'phpdoc_no_alias_tag' => ['replacements' => ['property-read' => 'property', 'property-write' => 'property']],
	'phpdoc_no_empty_return' => true,
	'phpdoc_no_package' => false,
	'phpdoc_no_useless_inheritdoc' => true,
	'phpdoc_order' => true,
	'phpdoc_param_order' => true,
	'phpdoc_return_self_reference' => true,
	'phpdoc_scalar' => true,
	'phpdoc_separation' => true,
	'phpdoc_single_line_var_spacing' => true,
	'phpdoc_summary' => true,
	'phpdoc_tag_type' => ['tags' => ['inheritDoc' => 'inline']],
	'phpdoc_trim' => true,
	'phpdoc_trim_consecutive_blank_line_separation' => true,
	'phpdoc_types' => true,
	'phpdoc_types_order' => ['null_adjustment' => 'always_last', 'sort_algorithm' => 'none'],
	'phpdoc_var_without_name' => true,
	'return_type_declaration' => ['space_before' => 'none'],
	'single_blank_line_at_eof' => true,
	'single_import_per_statement' => true,
	'single_line_after_imports' => true,
	'single_line_comment_spacing' => true,
	'single_line_comment_style' => ['comment_types' => ['hash']],
	'single_space_after_construct' => true,
	'space_after_semicolon' => ['remove_in_empty_for_expressions' => true],
	'standardize_increment' => true,
	'standardize_not_equals' => true,
	'strict_comparison' => true,
	'switch_case_semicolon_to_colon' => true,
	'switch_case_space' => true,
	'trailing_comma_in_multiline' => true,
	'trim_array_spaces' => true,
	'types_spaces' => true,
	'visibility_required' => ['elements' => ['property', 'method']],
	'whitespace_after_comma_in_array' => true,
	'yoda_style' => ['equal' => false, 'identical' => false, 'less_and_greater' => false],
	'php_unit_construct' => true,
])
	->setFinder($finder)
	->setIndent("    ")
	->setLineEnding("\n");
