import { ObjectEntity } from './object'
import { TObject } from './object.types'

export const mockObjectData = (): TObject[] => [
	{
		'@self': {
			id: '1234a1e5-b54d-43ad-abd1-4b5bff5fcd3f',
			uuid: 'uuid-1234a1e5-b54d-43ad-abd1-4b5bff5fcd3f',
			uri: 'https://example.com/character/1234a1e5-b54d-43ad-abd1-4b5bff5fcd3f',
			version: '1.0.0',
			register: 'Character Register',
			schema: 'character_schema',
			schemaVersion: '1.0.0',
			relations: JSON.stringify({ key: 'value' }),
			files: JSON.stringify({ key: 'value' }),
			folder: 'https://example.com/character/1234a1e5-b54d-43ad-abd1-4b5bff5fcd3f',
			textRepresentation: 'Character object description',
			locked: ['token1', 'token2'],
			owner: 'user1',
			authorization: [{ role: 'admin', permissions: ['read', 'write'] }],
			application: 'OpenRegister',
			organisation: 'Example Org',
			validation: [{ status: 'valid', errors: [] }],
			deleted: null,
			geo: [{ lat: 52.3676, lon: 4.9041 }],
			retention: [{ period: '7y', reason: 'legal' }],
			size: '1024',
			created: new Date().toISOString(),
			updated: new Date().toISOString(),
			published: new Date().toISOString(),
			depublished: null,
		},
	},
	{
		'@self': {
			id: '5678a1e5-b54d-43ad-abd1-4b5bff5fcd3f',
			uuid: 'uuid-5678a1e5-b54d-43ad-abd1-4b5bff5fcd3f',
			uri: 'https://example.com/item/5678a1e5-b54d-43ad-abd1-4b5bff5fcd3f',
			version: null,
			register: 'Item Register',
			schema: 'item_schema',
			schemaVersion: null,
			relations: JSON.stringify({ key: 'value' }),
			files: JSON.stringify({ key: 'value' }),
			folder: 'https://example.com/item/5678a1e5-b54d-43ad-abd1-4b5bff5fcd3f',
			textRepresentation: null,
			locked: null,
			owner: 'user2',
			authorization: null,
			application: null,
			organisation: null,
			validation: null,
			deleted: null,
			geo: null,
			retention: null,
			size: '512',
			created: new Date().toISOString(),
			updated: new Date().toISOString(),
			published: null,
			depublished: null,
		},
	},
]

export const mockObject = (data: TObject[] = mockObjectData()): TObject[] => data.map(item => new ObjectEntity(item))
